In [2]:
import pandas as pd
from io import StringIO
from IPython.display import display

In [3]:
CSV_TEXT = """sale_id,date,branch,product,unit_price,quantity,discount,payment
1,2026-08-24,Central,Coffee,3.50,2,0,Card
2,2026-08-24,Central,Tea,2.50,3,0,Cash
3,2026-08-24,Central,Cake,4.00,1,0.10,Card
4,2026-08-24,Station,Sandwich,6.00,2,0,Card
5,2026-08-24,Station,coffee,3.50,4,0.10,Cash
6,2026-08-25,Central, Coffee ,3.50,3,,Card
7,2026-08-25,Central,Sandwich,6.00,1,0.10,Card
8,2026-08-25,Station,Tea,2.50,5,0,Cash
9,2026-08-25,Station,Cake,4.00,2,0.20,Card
10,2026-08-25,Station,Coffee,3.50,1,0,
11,2026-08-26,Central,Tea,2.50,2,0,Cash
12,2026-08-26,Central,Cake,4.00,3,0,Card
13,2026-08-26,Station,Sandwich,6.00,3,0.10,Card
14,2026-08-26,Station,Coffee,3.50,2,0,Card
15,2026-08-26,Central,Coffee,3.50,4,0.20,Cash
16,2026-08-27,Central,Sandwich,6.00,2,0,Card
17,2026-08-27,Central,Cake,4.00,2,,Cash
18,2026-08-27,Station,Tea,2.50,4,0.10,Card
19,2026-08-27,Station,Coffee,3.50,3,0,Card
20,2026-08-27,Central,Tea,2.50,1,0,Card
5,2026-08-24,Station,coffee,3.50,4,0.10,Cash
"""

raw = pd.read_csv(StringIO(CSV_TEXT))

menu = pd.DataFrame({
    "product": ["Coffee", "Tea", "Cake", "Sandwich"],
    "category": ["Drink", "Drink", "Food", "Food"],
    "unit_cost": [1.00, 0.50, 1.50, 2.80],
})

raw.head()

,sale_id,date,branch,product,unit_price,quantity,discount,payment
0,1,2026-08-24,Central,Coffee,3.5,2,0.0,Card
1,2,2026-08-24,Central,Tea,2.5,3,0.0,Cash
2,3,2026-08-24,Central,Cake,4.0,1,0.1,Card
3,4,2026-08-24,Station,Sandwich,6.0,2,0.0,Card
4,5,2026-08-24,Station,coffee,3.5,4,0.1,Cash

In [4]:
print("Rows, columns:", raw.shape)
raw.info()

Rows, columns: (21, 8)
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sale_id     21 non-null     int64
 1   date        21 non-null     str
 2   branch      21 non-null     str
 3   product     21 non-null     str
 4   unit_price  21 non-null     float64
 5   quantity    21 non-null     int64
 6   discount    19 non-null     float64
 7   payment     20 non-null     str
dtypes: float64(2), int64(2), str(4)
memory usage: 1.4 KB

In [5]:
display(raw["product"])
display(raw[["product", "quantity"]])

0       Coffee
1          Tea
2         Cake
3     Sandwich
4       coffee
5      Coffee
6     Sandwich
7          Tea
8         Cake
9       Coffee
10         Tea
11        Cake
12    Sandwich
13      Coffee
14      Coffee
15    Sandwich
16        Cake
17         Tea
18      Coffee
19         Tea
20      coffee
Name: product, dtype: str

     product  quantity
0     Coffee         2
1        Tea         3
2       Cake         1
3   Sandwich         2
4     coffee         4
5    Coffee          3
6   Sandwich         1
7        Tea         5
8       Cake         2
9     Coffee         1
10       Tea         2
11      Cake         3
12  Sandwich         3
13    Coffee         2
14    Coffee         4
15  Sandwich         2
16      Cake         2
17       Tea         4
18    Coffee         3
19       Tea         1
20    coffee         4

In [6]:
# TODO: Count missing values per column and exact duplicate rows. Inspect distinct product

print(raw.isna().sum()) 
print(raw.duplicated().sum())
print(raw["product"].unique())

sale_id       0
date          0
branch        0
product       0
unit_price    0
quantity      0
discount      2
payment       1
dtype: int64
1
<StringArray>
['Coffee', 'Tea', 'Cake', 'Sandwich', 'coffee', ' Coffee ']
Length: 6, dtype: str

In [7]:
# TODO: Display every copy of each duplicated row, then display rows with missing discounts
display(raw[raw.duplicated(keep=False)])
display(raw[raw["discount"].isna()])

,sale_id,date,branch,product,unit_price,quantity,discount,payment
4,5,2026-08-24,Station,coffee,3.5,4,0.1,Cash
20,5,2026-08-24,Station,coffee,3.5,4,0.1,Cash

,sale_id,date,branch,product,unit_price,quantity,discount,payment
5,6,2026-08-25,Central,Coffee,3.5,3,NaN,Card
16,17,2026-08-27,Central,Cake,4.0,2,NaN,Cash

In [8]:
sales = raw.drop_duplicates().copy()
sales["product"] = sales["product"].str.strip().str.title()
sales["discount"] = sales["discount"].fillna(0)
sales["payment"] = sales["payment"].fillna("Unknown")
assert sales["sale_id"].is_unique, "Conflicting sale IDs need investigation."
display(sales.head())

,sale_id,date,branch,product,unit_price,quantity,discount,payment
0,1,2026-08-24,Central,Coffee,3.5,2,0.0,Card
1,2,2026-08-24,Central,Tea,2.5,3,0.0,Cash
2,3,2026-08-24,Central,Cake,4.0,1,0.1,Card
3,4,2026-08-24,Station,Sandwich,6.0,2,0.0,Card
4,5,2026-08-24,Station,Coffee,3.5,4,0.1,Cash

In [9]:
display(sales["quantity"] >= 3)
sales[sales["quantity"] >= 3]

0     False
1      True
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9     False
10    False
11     True
12     True
13    False
14     True
15    False
16    False
17     True
18     True
19    False
Name: quantity, dtype: bool

,sale_id,date,branch,product,unit_price,quantity,discount,payment
1,2,2026-08-24,Central,Tea,2.5,3,0.0,Cash
4,5,2026-08-24,Station,Coffee,3.5,4,0.1,Cash
5,6,2026-08-25,Central,Coffee,3.5,3,0.0,Card
7,8,2026-08-25,Station,Tea,2.5,5,0.0,Cash
11,12,2026-08-26,Central,Cake,4.0,3,0.0,Card
12,13,2026-08-26,Station,Sandwich,6.0,3,0.1,Card
14,15,2026-08-26,Central,Coffee,3.5,4,0.2,Cash
17,18,2026-08-27,Station,Tea,2.5,4,0.1,Card
18,19,2026-08-27,Station,Coffee,3.5,3,0.0,Card

In [10]:
mask = (sales["branch"] == "Central") & (sales["quantity"] >= 3)
sales.loc[mask, ["sale_id", "product", "quantity"]]

    sale_id product  quantity
1         2     Tea         3
5         6  Coffee         3
11       12    Cake         3
14       15  Coffee         4

In [11]:
# TODO: Find Station coffee sales with quantity at least 3. Show sale_id, product, and quantity.
mask = ((sales["product"] == "Coffee") & (sales["branch"] == "Station") & (sales["quantity"] >= 3))
sales.loc[mask, ["sale_id", "product", "quantity"]]

    sale_id product  quantity
4         5  Coffee         4
18       19  Coffee         3

In [12]:
# TODO: Find Tea or Cake sales paid by card.

mask = (((sales["product"] == "Tea") | (sales["product"] == "Cake")) & (sales["payment"] == "Card"))
display(sales[mask])

,sale_id,date,branch,product,unit_price,quantity,discount,payment
2,3,2026-08-24,Central,Cake,4.0,1,0.1,Card
8,9,2026-08-25,Station,Cake,4.0,2,0.2,Card
11,12,2026-08-26,Central,Cake,4.0,3,0.0,Card
17,18,2026-08-27,Station,Tea,2.5,4,0.1,Card
19,20,2026-08-27,Central,Tea,2.5,1,0.0,Card

In [13]:
sales["gross_revenue"] = sales["unit_price"] * sales["quantity"]
sales["revenue"] = (sales["gross_revenue"] * (1 - sales["discount"])).round(2)
sales["discount_amount"] = (sales["gross_revenue"] - sales["revenue"]).round(2)
sales.loc[sales["sale_id"] == 5, ["gross_revenue", "discount_amount", "revenue"]]

   gross_revenue  discount_amount  revenue
4           14.0              1.4     12.6

In [14]:
# TODO: Calculate total units, gross revenue, revenue, and discount amount. Show the three highest-revenue individual sales.
sales[["quantity", "gross_revenue", "revenue", "discount_amount"]].sum()
display(sales.sort_values("revenue", ascending=False).head(3))

,sale_id,date,branch,product,unit_price,quantity,discount,payment,gross_revenue,revenue,discount_amount
12,13,2026-08-26,Station,Sandwich,6.0,3,0.1,Card,18.0,16.2,1.8
4,5,2026-08-24,Station,Coffee,3.5,4,0.1,Cash,14.0,12.6,1.4
7,8,2026-08-25,Station,Tea,2.5,5,0.0,Cash,12.5,12.5,0.0

In [15]:
# TODO: Find discounted sales with revenue of at least 10. Show sale_id, product, discount, and revenue. Keep sales unchanged.
mask = ((sales["discount"] > 0) & (sales["revenue"] >= 10))
sales.loc[mask, ["sale_id", "product", "discount", "revenue"]]

    sale_id   product  discount  revenue
4         5    Coffee       0.1     12.6
12       13  Sandwich       0.1     16.2
14       15    Coffee       0.2     11.2

In [16]:
product_summary = sales.groupby("product", as_index=False).agg(
    sales_count=("sale_id", "size"),
    units=("quantity", "sum"),
    revenue=("revenue", "sum"),
)
product_summary = product_summary.sort_values("revenue", ascending=False)
product_summary

    product  sales_count  units  revenue
1    Coffee            7     19     62.3
2  Sandwich            4      8     45.6
3       Tea            5     15     36.5
0      Cake            4      8     30.0

In [17]:
# TODO: Group by branch. Calculate sales count, units, total revenue, and mean revenue per sale. Rank branches by total revenue.
branch_summary = sales.groupby("branch", as_index= False).agg(
    sales_count=("sale_id", "size"),
    units=("quantity", "sum"),
    revenue=("revenue", "sum"),
    avg_transaction=("revenue", "mean")
)
branch_summary = branch_summary.sort_values("revenue", ascending=True)
branch_summary

    branch  sales_count  units  revenue  avg_transaction
0  Central           11     24     84.7         7.700000
1  Station            9     26     89.7         9.966667

In [18]:
# TODO: Group by branch and product. Show sales count, units, and revenue, sorted by branch and descending revenue.
branch_product_summary = sales.groupby(["branch", "product"], as_index=False).agg(
    sales_count=("sale_id", "size"),
    units=("quantity", "sum"),
    revenue=("revenue", "sum"),
)
branch_product_summary = branch_product_summary.sort_values(["branch", "revenue"], ascending=[True, False])
branch_product_summary

    branch   product  sales_count  units  revenue
1  Central    Coffee            3      9     28.7
0  Central      Cake            3      6     23.6
2  Central  Sandwich            2      3     17.4
3  Central       Tea            3      6     15.0
5  Station    Coffee            4     10     33.6
6  Station  Sandwich            2      5     28.2
7  Station       Tea            2      9     21.5
4  Station      Cake            1      2      6.4

In [ ]:
display(menu)
enriched = sales.merge(menu, on="product", how="left", validate="many_to_one")
assert len(enriched) == len(sales)
assert enriched["unit_cost"].notna().all(), "Some products are missing ingredient costs."
enriched["ingredient_cost"] = (enriched["quantity"] * enriched["unit_cost"]).round(2)
enriched["contribution"] = (enriched["revenue"] - enriched["ingredient_cost"]).round(2)
enriched.head()

    product category  unit_cost
0    Coffee    Drink        1.0
1       Tea    Drink        0.5
2      Cake     Food        1.5
3  Sandwich     Food        2.8

,sale_id,date,branch,product,unit_price,quantity,discount,payment,gross_revenue,revenue,discount_amount,category,unit_cost,ingredient_cost,contribution
0,1,2026-08-24,Central,Coffee,3.5,2,0.0,Card,7.0,7.0,0.0,Drink,1.0,2.0,5.0
1,2,2026-08-24,Central,Tea,2.5,3,0.0,Cash,7.5,7.5,0.0,Drink,0.5,1.5,6.0
2,3,2026-08-24,Central,Cake,4.0,1,0.1,Card,4.0,3.6,0.4,Food,1.5,1.5,2.1
3,4,2026-08-24,Station,Sandwich,6.0,2,0.0,Card,12.0,12.0,0.0,Food,2.8,5.6,6.4
4,5,2026-08-24,Station,Coffee,3.5,4,0.1,Cash,14.0,12.6,1.4,Drink,1.0,4.0,8.6

In [ ]:
# TODO: Rank products by total contribution. Compare this with the revenue ranking. Calculate total contribution across all sales.

In [ ]:
# TODO: Remove Tea from a copy of menu. Left-merge sales with this lookup using indicator=True and find unmatched sales. Compare with an inner merge. Keep menu and enriched unchanged.

In [ ]:
enriched["date"] = pd.to_datetime(enriched["date"], format="%Y-%m-%d")
daily = enriched.groupby("date")["revenue"].sum().sort_index()
display(daily)

branch_product_grid = enriched.pivot_table(
    index="branch", columns="product", values="revenue",
    aggfunc="sum", fill_value=0,
)
display(branch_product_grid)

date
2026-08-24    42.7
2026-08-25    38.3
2026-08-26    51.4
2026-08-27    42.0
Name: revenue, dtype: float64

product  Cake  Coffee  Sandwich   Tea
branch
Central  23.6    28.7      17.4  15.0
Station   6.4    33.6      28.2  21.5

In [ ]:
# TODO: Build a pivot table with dates as rows, branches as columns, and summed revenue as values. Find the highest-revenue day. Extract weekday names with .dt.day_name().

In [ ]:
# TODO: From enriched, select Station sales on or after 2026-08-25. Group by product and show units, revenue, and contribution. Rank by contribution. Export station_report.csv without an index.

In [ ]:
# TODO: Use a de-duplicated copy of raw without filling missing payments. Group by branch and compare .size() with .count() on payment.

In [ ]:
# TODO: Find the highest-revenue product in each branch. Return all tied winners when totals are equal.

In [ ]:
# TODO: Calculate each product's percentage of its branch's revenue. Use groupby(...).transform("sum"). Check that percentages sum to approximately 100 within each branch.

In [ ]:
# TODO: For each product, calculate mean revenue per sale and revenue per unit.

In [ ]:
# TODO: Add a second Coffee row to a copy of menu. Merge with validate="many_to_one" and catch pd.errors.MergeError. Repeat without validation and compare row count and total revenue with sales.

In [ ]:
# TODO: Calculate contribution as a percentage of revenue for each product and for the whole cafe. Compare the overall ratio of totals with the mean of row-level percentages.

In [ ]:
# TODO: Export enriched to clean_sales.csv without an index. Read it into reloaded using parse_dates=["date"]. Check row count and total revenue.